languageCode: en-us
title: Posts
baseURL: https://cespira.github.io/
theme: hugo-theme-massively
googleanalytics: ''
disqusShortname: ''
disableKinds:
  - taxonomy
  - taxonomyTerm
languages:
  en:
    languageName: English
  # es:
  #   languageName: Español
  #   title: Massively - Versión Español
